[book]
title = "San Min Zhu Yi"
authors = ["zhushunshui"]

language = "zh-CN"
multilingual = false
src = "src"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

































